# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "jldt-bundles"
client_id = "2e669c4ea09cbd82703810194af7878b"
application_url = "https://jl-bundle-builder.fly.dev"
embedded = true

[access_scopes]
# Learn mqore at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://jl-bundle-builder.fly.dev/auth/callback" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "johnlewisdesign.myshopify.com"
